menubar: false
toolbar:
  - styleselect | bold italic | undo redo | uploadimage | link, alignleft aligncenter alignright | outdent indent | bullist numlist | media
plugins:
  - uploadimage
  - link
  - media
  - lists
